services:
  vosk-en:
    image: alphacep/kaldi-vosk-server
    container_name: meet-vosk-en
    # you should run `mkdir -p ./vosk/models`
    # and download models from https://alphacephei.com/vosk/models
    # and place them in `./vosk/models`
    volumes:
      - ./vosk/models:/opt/vosk-models
    working_dir: /opt/vosk-server/websocket
    # using the vosk-model-en-us-0.22-lgraph model for English
    entrypoint: ["python3", "./asr_server.py", "/opt/vosk-models/vosk-model-en-us-0.22-lgraph"]
    expose:
      - 2700
    networks:
      meet.jitsi:

  vosk-zh-small:
    image: alphacep/kaldi-vosk-server
    container_name: meet-vosk-zh-sm
    volumes:
      - ./vosk/models:/opt/vosk-models
    working_dir: /opt/vosk-server/websocket
    # using the vosk-model-small-cn-0.22 model for Chinese
    entrypoint: ["python3", "./asr_server.py", "/opt/vosk-models/vosk-model-small-cn-0.22"]
    expose:
      - 2700
    networks:
      meet.jitsi:

  vosk-zh:
    image: alphacep/kaldi-vosk-server
    container_name: meet-vosk-zh
    volumes:
      - ./vosk/models:/opt/vosk-models
    working_dir: /opt/vosk-server/websocket
    # using the vosk-model-cn-0.22 model for Chinese
    entrypoint: ["python3", "./asr_server.py", "/opt/vosk-models/vosk-model-cn-0.22"]
    expose:
      - 2700
    networks:
      meet.jitsi:
